version: '3'

services:
  frontend:
      build: ./movie-search
      container_name: frontend
      hostname: frontend
      ports:
        - "3000:3000"
      expose:
        - "3000"
      depends_on:
        - backend
      environment:
        - BACK_END_SERVICE_HOST=backend:8000

  backend:
    container_name: backend
    hostname: backend

    build: ./backend
    ports:
    - "8000:8000"
    expose:
      - "8000"